import { createSlice } from '@reduxjs/toolkit';

interface Country {
  id: string;
  name: string;
}

interface CountriesState {
  countries: Country[];
}

const initialState: CountriesState = {
  countries: [
    { id: '1', name: 'Afghanistan' },
    { id: '2', name: 'Albania' },
    { id: '3', name: 'Algeria' },
    { id: '4', name: 'Andorra' },
    { id: '5', name: 'Angola' },
    { id: '6', name: 'Antigua and Barbuda' },
    { id: '7', name: 'Argentina' },
    { id: '8', name: 'Armenia' },
    { id: '9', name: 'Australia' },
    { id: '10', name: 'Austria' },
    { id: '11', name: 'Azerbaijan' },
    { id: '12', name: 'Bahamas' },
    { id: '13', name: 'Bahrain' },
    { id: '14', name: 'Bangladesh' },
    { id: '15', name: 'Barbados' },
    { id: '16', name: 'Belarus' },
    { id: '17', name: 'Belgium' },
    { id: '18', name: 'Belize' },
    { id: '19', name: 'Benin' },
    { id: '20', name: 'Bhutan' },
    { id: '21', name: 'Bolivia' },
    { id: '22', name: 'Bosnia and Herzegovina' },
    { id: '23', name: 'Botswana' },
    { id: '24', name: 'Brazil' },
    { id: '25', name: 'Brunei' },
    { id: '26', name: 'Bulgaria' },
    { id: '27', name: 'Burkina Faso' },
    { id: '28', name: 'Burundi' },
    { id: '29', name: 'Cabo Verde' },
    { id: '30', name: 'Cambodia' },
    { id: '31', name: 'Cameroon' },
    { id: '32', name: 'Canada' },
    { id: '33', name: 'Central African Republic' },
    { id: '34', name: 'Chad' },
    { id: '35', name: 'Chile' },
    { id: '36', name: 'China' },
    { id: '37', name: 'Colombia' },
    { id: '38', name: 'Comoros' },
    { id: '39', name: 'Congo (Congo-Brazzaville)' },
    { id: '40', name: 'Congo (Congo-Kinshasa)' },
    { id: '41', name: 'Costa Rica' },
    { id: '42', name: 'Croatia' },
    { id: '43', name: 'Cuba' },
    { id: '44', name: 'Cyprus' },
    { id: '45', name: 'Czechia' },
    { id: '46', name: 'Denmark' },
    { id: '47', name: 'Djibouti' },
    { id: '48', name: 'Dominica' },
    { id: '49', name: 'Dominican Republic' },
    { id: '50', name: 'Ecuador' },
    { id: '51', name: 'Egypt' },
    { id: '52', name: 'El Salvador' },
    { id: '53', name: 'Equatorial Guinea' },
    { id: '54', name: 'Eritrea' },
    { id: '55', name: 'Estonia' },
    { id: '56', name: 'Eswatini' },
    { id: '57', name: 'Ethiopia' },
    { id: '58', name: 'Fiji' },
    { id: '59', name: 'Finland' },
    { id: '60', name: 'France' },
    { id: '61', name: 'Gabon' },
    { id: '62', name: 'Gambia' },
    { id: '63', name: 'Georgia' },
    { id: '64', name: 'Germany' },
    { id: '65', name: 'Ghana' },
    { id: '66', name: 'Greece' },
    { id: '67', name: 'Grenada' },
    { id: '68', name: 'Guatemala' },
    { id: '69', name: 'Guinea' },
    { id: '70', name: 'Guinea-Bissau' },
    { id: '71', name: 'Guyana' },
    { id: '72', name: 'Haiti' },
    { id: '73', name: 'Honduras' },
    { id: '74', name: 'Hungary' },
    { id: '75', name: 'Iceland' },
    { id: '76', name: 'India' },
    { id: '77', name: 'Indonesia' },
    { id: '78', name: 'Iran' },
    { id: '79', name: 'Iraq' },
    { id: '80', name: 'Ireland' },
    { id: '81', name: 'Israel' },
    { id: '82', name: 'Italy' },
    { id: '83', name: 'Jamaica' },
    { id: '84', name: 'Japan' },
    { id: '85', name: 'Jordan' },
    { id: '86', name: 'Kazakhstan' },
    { id: '87', name: 'Kenya' },
    { id: '88', name: 'Kiribati' },
    { id: '89', name: 'Kuwait' },
    { id: '90', name: 'Kyrgyzstan' },
    { id: '91', name: 'Laos' },
    { id: '92', name: 'Latvia' },
    { id: '93', name: 'Lebanon' },
    { id: '94', name: 'Lesotho' },
    { id: '95', name: 'Liberia' },
    { id: '96', name: 'Libya' },
    { id: '97', name: 'Liechtenstein' },
    { id: '98', name: 'Lithuania' },
    { id: '99', name: 'Luxembourg' },
    { id: '100', name: 'Madagascar' },
    { id: '101', name: 'Malawi' },
    { id: '102', name: 'Malaysia' },
    { id: '103', name: 'Maldives' },
    { id: '104', name: 'Mali' },
    { id: '105', name: 'Malta' },
    { id: '106', name: 'Mexico' },
    { id: '107', name: 'Moldova' },
    { id: '108', name: 'Monaco' },
    { id: '109', name: 'Mongolia' },
    { id: '110', name: 'Montenegro' },
  ],
};

const countriesSlice = createSlice({
  name: 'countries',
  initialState,
  reducers: {},
});

export default countriesSlice.reducer;
